# Phải đổi service ingress-nginx-controller  thành LoadBalancer
# kubectl patch svc ingress-nginx-controller -n ingress-nginx -p "{\"spec\": {\"type\": \"LoadBalancer\"}}"

# Chạy minikube tunnel
#  EXTERNAL-IP  đó sẽ gán vào file  C:\Windows\System32\drivers\etc\hosts

# http://hivespace.local/api/v1/users/signup

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hivespaceapp-ingress
  annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hivespaceapp-service
                port:
                  number: 80
