apiVersion: v1
kind: ConfigMap
metadata:
  name: hivespace-configmap
data:
{{- $envPath := printf "config/%s/*.json" .Values.ASPNETCORE_ENVIRONMENT }}
{{- range $path, $content := .Files.Glob $envPath }}
  {{ base $path }}: |
{{ $content | indent 4 }}
{{- end }}