apiVersion: v1
kind: ConfigMap
metadata:
  name: hivespace-configmap
data:
  appsettings.json: |
    {
      "AzureBlobStorage": {
        "Connectionstring": "DefaultEndpointsProtocol=https;AccountName=youraccount;AccountKey=yourkey;EndpointSuffix=core.windows.net"
      }
    }
