apiVersion: v1
kind: ConfigMap
metadata:
  name: hivespace-configmap
data:
  appsettings.json: |
    {
        "Logging": {
            "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
            }
        },
        "AzureBlobStorage": {
            "ConnectionString": "test"
        },
        "Postgres": {
            "ConnectionString": "Server=hivespace-postgres.postgres.database.azure.com;Database=HiveSpaceDB;Port=5432;User Id=dev5k;Password=Ecommerce0123;Ssl Mode=Require;"
        },
        "Redis": {
            "ConnectionString": "52.175.16.37:6379,password=Ecommerce0123",
            "InstanceName": "HiveSpace_"
        }
    }