apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivespace-deployment
  labels:
    app: hivespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hivespaceapp
  template:
    metadata:
      labels:
        app: hivespaceapp
    spec:
      containers:
      - name: hivespaceapp
        image: dblmint/hivespace-hivespaceapp:142
        ports:
        - containerPort: 8080  
      volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: appsettings-config
