apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivespace-deployment
  labels:
    app: hivespace
spec:
  replicas: {{Values.replicas}}
  selector:
    matchLabels:
      app: hivespaceapp
  template:
    metadata:
      labels:
        app: hivespaceapp
    spec:
      containers:
      - name: hivespaceapp
        image: dblmint/hivespace-hivespaceapp:161
        ports:
        - containerPort: 8080 
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: {{.Values.ASPNETCORE_ENVIRONMENT}} 
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: hivespace-configmap
